"""Add game and inning models

Revision ID: 010b8f8b9b7a
Revises: a3894c595d54
Create Date: 2025-06-03 15:56:01.373141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010b8f8b9b7a'
down_revision: Union[str, None] = 'a3894c595d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
