"""Add game and inning models

Revision ID: a3894c595d54
Revises: add_hitter_handedness_to_pitch
Create Date: 2025-06-03 15:53:25.899232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3894c595d54'
down_revision: Union[str, None] = 'add_hitter_handedness_to_pitch'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pitch_id', table_name='pitch')
    op.drop_table('pitch')
    op.drop_index('ix_transitiontable_id', table_name='transitiontable')
    op.drop_table('transitiontable')
    op.drop_index('ix_pitcher_id', table_name='pitcher')
    op.drop_index('ix_pitcher_name', table_name='pitcher')
    op.drop_table('pitcher')
    op.drop_index('ix_predictionhistory_id', table_name='predictionhistory')
    op.drop_table('predictionhistory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictionhistory',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('pitcher_id', sa.VARCHAR(), nullable=True),
    sa.Column('predicted_pitch', sa.VARCHAR(), nullable=True),
    sa.Column('actual_pitch', sa.VARCHAR(), nullable=True),
    sa.Column('was_correct', sa.BOOLEAN(), nullable=True),
    sa.Column('count', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['pitcher_id'], ['pitcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictionhistory_id', 'predictionhistory', ['id'], unique=False)
    op.create_table('pitcher',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('team', sa.VARCHAR(), nullable=True),
    sa.Column('number', sa.INTEGER(), nullable=True),
    sa.Column('hand', sa.VARCHAR(), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pitcher_name', 'pitcher', ['name'], unique=False)
    op.create_index('ix_pitcher_id', 'pitcher', ['id'], unique=False)
    op.create_table('transitiontable',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('pitcher_id', sa.VARCHAR(), nullable=True),
    sa.Column('count', sa.VARCHAR(), nullable=True),
    sa.Column('last_pitch', sa.VARCHAR(), nullable=True),
    sa.Column('next_pitch', sa.VARCHAR(), nullable=True),
    sa.Column('transition_count', sa.INTEGER(), nullable=True),
    sa.Column('probability', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('pitch_result', sa.VARCHAR(), nullable=True),
    sa.Column('play_result', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('hitter_handedness', sa.VARCHAR(), server_default=sa.text("'R'"), nullable=False),
    sa.ForeignKeyConstraint(['pitcher_id'], ['pitcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transitiontable_id', 'transitiontable', ['id'], unique=False)
    op.create_table('pitch',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('pitcher_id', sa.VARCHAR(), nullable=True),
    sa.Column('count', sa.VARCHAR(), nullable=True),
    sa.Column('pitch_type', sa.VARCHAR(length=2), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('pitch_result', sa.VARCHAR(length=15), nullable=True),
    sa.Column('play_result', sa.VARCHAR(length=9), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('hitter_handedness', sa.VARCHAR(), server_default=sa.text("'R'"), nullable=False),
    sa.ForeignKeyConstraint(['pitcher_id'], ['pitcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pitch_id', 'pitch', ['id'], unique=False)
    # ### end Alembic commands ###
